### ISSUE TITLE
Error when following readme

### ISSUE THREAD

**Issue by Akxe** [tinesoft/ngx-uptodate#16]
# Bug Report or Feature Request (mark with an `x`)

```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

## ngx-uptodate Version?
v1.1.0

## Repro steps
Create action.yml and copy snippet from readme into it:

```
name: "Update Angular Action"
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  push

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here !
        uses: tinesoft/ngx-uptodate@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

## The log given by the failure
```
Run tinesoft/ngx-uptodate@master
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/tinesoft/ngx-uptodate/master/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/tinesoft/ngx-uptodate/master/lib/main.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/tinesoft/ngx-uptodate/master/lib/main.js'
  ]
}
```

## Desired functionality
No error... A text above/below snippet should inform the user to switch master with current version of the action. ex.: `uses: tinesoft/ngx-uptodate@**WRITE_CURRENT_VERSION_HERE**`

## Mention any other details that might be useful
Writing `v1.1.0``instead of `master` will make it work
